version: "2"
services:
  stats:
    build: ika-stats
    restart: always
    hostname: ikastats
    domainname: gosu.fi
    ports:
      - "0.0.0.0:5573:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ikastats
    volumes:
      - /srv/data/ikastats/mysql:/var/lib/mysql
